version: "2.0"

services:
  vue-admin-system-demo:
    image: 'your-company.harbor.com/admin-system/vue-admin-system-demo:0.0.1'
    restart: always
    container_name: vue-admin-system-demo
    ports:
      - "80:80"
    mem_limit: 2048M
    logging:
      options:
        max-size: 100m
    networks:
      - devops
networks:
  devops:
    external:
      name: devops01